.TH "/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/doc/ Directory Reference" 3 "Fri Aug 17 2012" "Version 1.8.0" "avr-libc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/tools/hudson/workspace/avr8-gnu-toolchain/src/avr-libc/doc/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBexamples\fP"
.br
.in -1c
